// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Infrastructure.Data;

#nullable disable

namespace OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607130746_add initial migration")]
    partial class addinitialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Domain.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Entities.RuntimeMetricSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CpuDeltaCpuMs")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuDeltaWallMs")
                        .HasColumnType("double precision");

                    b.Property<int>("CpuLogicalProcessorCount")
                        .HasColumnType("integer");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<int?>("DbActiveConnections")
                        .HasColumnType("integer");

                    b.Property<int?>("DbIdleConnections")
                        .HasColumnType("integer");

                    b.Property<int?>("DbIdleInTransactionConnections")
                        .HasColumnType("integer");

                    b.Property<int?>("DbTotalConnections")
                        .HasColumnType("integer");

                    b.Property<double>("GcFragmentedMb")
                        .HasColumnType("double precision");

                    b.Property<int>("GcGen0Collections")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen0Delta")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen1Collections")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen1Delta")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen2Collections")
                        .HasColumnType("integer");

                    b.Property<int>("GcGen2Delta")
                        .HasColumnType("integer");

                    b.Property<double>("GcHeapSizeMb")
                        .HasColumnType("double precision");

                    b.Property<double>("GcHighMemoryLoadThresholdMb")
                        .HasColumnType("double precision");

                    b.Property<double>("GcMemoryLoadMb")
                        .HasColumnType("double precision");

                    b.Property<double>("GcTotalAvailableMemoryMb")
                        .HasColumnType("double precision");

                    b.Property<int>("ProcessThreadCount")
                        .HasColumnType("integer");

                    b.Property<double>("RamGcHeapMb")
                        .HasColumnType("double precision");

                    b.Property<double>("RamGcMemoryLoadMb")
                        .HasColumnType("double precision");

                    b.Property<double>("RamManagedHeapMb")
                        .HasColumnType("double precision");

                    b.Property<double>("RamPrivateMemoryMb")
                        .HasColumnType("double precision");

                    b.Property<double>("RamWorkingSetMb")
                        .HasColumnType("double precision");

                    b.Property<int?>("SocketTotalConnections")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolAvailableIoCompletionThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolAvailableWorkerThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolBusyWorkerThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolMaxIoCompletionThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolMaxWorkerThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolMinIoCompletionThreads")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadPoolMinWorkerThreads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.ToTable("RuntimeMetricSnapshots", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Entities.SpikeReportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CorrelationWindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CorrelationWindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RuntimeMetricSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("RuntimeMetricSnapshotId");

                    b.ToTable("SpikeReports", (string)null);
                });

            modelBuilder.Entity("OrderService.Domain.Entities.SpikeReportRecord", b =>
                {
                    b.HasOne("OrderService.Domain.Entities.RuntimeMetricSnapshotRecord", "Snapshot")
                        .WithMany()
                        .HasForeignKey("RuntimeMetricSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
