{
 "title": "Microservices Observability - Metrics & DB",
 "tags": [
  "dotnet",
  "microservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_time_total[1m]) * 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Memory Working Set (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Database Query Execution Time (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_client_commands_duration_bucket[5m])) by (le, service_name))",
     "legendFormat": "{{service_name}} - 95th Percentile"
    }
   ]
  },
  {
   "title": "Database Connection Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "db_client_connections_usage", "legendFormat": "{{service_name}} - {{state}}" }
   ]
  }
 ]
}