{
 "title": "Microservices RED Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(http_server_request_duration_seconds_count, exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate (Requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=~\"$service\"}[5m]))",
     "legendFormat": "Requests / sec"
    }
   ]
  },
  {
   "title": "Errors (500 Status Codes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=~\"$service\", http_response_status_code=~\"5..\"}[5m]))",
     "legendFormat": "Errors (5xx) / sec"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total{exported_job=~\"$service\"}[5m])) * 100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory (RAM) Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_memory_usage_bytes{exported_job=~\"$service\"})",
     "legendFormat": "RAM"
    }
   ]
  }
 ]
}