# Debezium Sink Configuration
# Debezium Sink Configuration
debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.streams.enabled=false
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=admin
debezium.sink.rabbitmq.connection.password=admin123
debezium.sink.rabbitmq.exchange=cdc.exchange
quarkus.http.port=0


# Debezium Source Configuration
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=write-db
debezium.source.database.port=5432
debezium.source.database.user=admin
debezium.source.database.password=pass
debezium.source.database.dbname=OrderDb
debezium.source.topic.prefix=order-server
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=order_slot
debezium.source.publication.name=order_pub
debezium.source.publication.autocreate.mode=disabled
debezium.source.schema.include.list=public
debezium.source.database.include.list=OrderDb
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat


# Format Configuration
debezium.format.key=json
debezium.format.value=json

